services:
  postgres:
    image: postgres:17-alpine
    container_name: pg_dev
    environment:
      POSTGRES_USER: lino
      POSTGRES_PASSWORD: lino
      POSTGRES_DB: simple_api
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev_network

  cloudbeaver:
    image: dbeaver/cloudbeaver:25
    container_name: cloudbeaver_dev
    ports:
      - "8978:8978"
    depends_on:
      - postgres
    networks:
      - dev_network
    environment:
      - CLOUDBEAVER_HOST=0.0.0.0
      - CLOUDBEAVER_PORT=8978

volumes:
  postgres_data:

networks:
  dev_network:
    driver: bridge
